### ISSUE TITLE
remove button issue

### ISSUE THREAD

**Issue by tufoinnkuo10** [Kingjosh007/awesome-books#4]
Hello @kingjosh007
Great Job you and your coding partner did there.. we just have one more small issue. 
The remove button does not remove a book when clicked, please endeavor to fix that.
cheers 😄 
happy coding.

**Comment by Kingjosh007** [comment]
Just fixed it. It was a type issue. I had to convert the idToDelete to a number, because it was a string by default.
For example, when trying to remove the first book, the code was looking for the book with id '1' instead of 1.
